services:
  - type: web
    name: finlock-api
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: finlock-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: finlock-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: finlock-db
          property: password
      - key: JWT_SECRET
        value: finlock-super-secret-key-that-is-at-least-32-characters-long
      - key: AES_KEY
        value: gYI00qX+W10Xr/ProqszHwkZOCVgFLP3u+x4Nm40E9I=
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        value: localhost:9092
      - key: JAVA_VERSION
        value: "21"

databases:
  - name: finlock-db
    plan: free
    databaseName: finlock
    user: finlock_user
