name: FinLock CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: finlock
          POSTGRES_USER: finlock_user
          POSTGRES_PASSWORD: finlock_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Kafka
        run: |
          docker run -d \
            --name finlock-kafka \
            --network host \
            -e KAFKA_NODE_ID=1 \
            -e KAFKA_PROCESS_ROLES=broker,controller \
            -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 \
            -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
            -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
            -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
            -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
            -e KAFKA_LOG_DIRS=/tmp/kraft-combined-logs \
            -e CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk \
            apache/kafka:3.7.0
          sleep 15

      - name: Build and run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/finlock
          SPRING_DATASOURCE_USERNAME: finlock_user
          SPRING_DATASOURCE_PASSWORD: finlock_pass
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379
          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          JWT_SECRET: test-secret-key-for-ci-at-least-32-characters-long
          AES_KEY: gYI00qX+W10Xr/ProqszHwkZOCVgFLP3u+x4Nm40E9I=
        run: mvn clean verify -q

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/